### ISSUE TITLE
Cannot run container on Raspberry Pi 3B

### ISSUE THREAD

**Issue by UntouchedWagons** [dbsentry/keyper-docker#1]
I've got a pi 3B running docker and built the container image. When I try to run the container it fails:

```docker run  -p 8080:80 -p 8443:443 --hostname keyper.untouchedwagons.site -it dbsentry/keyper
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/gunicorn/startup.sh to /container/run/startup/gunicorn
*** link /container/service/gunicorn/process.sh to /container/run/process/gunicorn/run
*** link /container/service/nginx/startup.sh to /container/run/startup/nginx
*** link /container/service/nginx/process.sh to /container/run/process/nginx/run
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
/container/tools/run:295: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  env_vars = yaml.load(f)
*** Running /container/run/startup/gunicorn...
mv: can't rename 'keyper': No such file or directory
*** /container/run/startup/gunicorn failed with status 1

*** In SystemExit
*** In finally
*** Killing all processes...```

**Comment by mlgupta** [comment]
Hi there,

It seems that when you build this, you did not download keyper submodule under modules directory.

Download that and try re-build.

$ git submodule init
$ git submodule update modules/keyper

**Comment by UntouchedWagons** [comment]
I did run those commands. I even rebuilt the container from scratch and it still fails the same way.

**Comment by mlgupta** [comment]
Few issues with the build script (empty dir ignored by git clone). It should be fixed now. Would you clone the latest code and try building again please.

**Comment by UntouchedWagons** [comment]
Yeah whatever you did did the track however when I go to either http://192.168.0.11 or https://192.168.0.11 I get an HTTP 403 error.

What does LDAP do in this project?

**Comment by mlgupta** [comment]
So, the container you build has REST API and OpenLDAP. Web Application is not open-sourced yet. If you want to experience full functionality, you can get the image published at docker hub or quay, it contains everything. The use of that image is free for personal use and for commercial as well, it is free for up to 20 servers. 

OpenLDAP is where all the users/hosts/groups are stored. It serves two purposes:
1) Authenticate user
2) Stores and returns SSH Public Key

There was lot of debate on why use OpenLDAP, but considering our long-term goals (i.e. sudoers functionality) we decided to use openLDAP vs any RDBMS.

Thx

**Comment by mlgupta** [comment]
One thing I forgot to mention is that the image you built, can be used using CLI. It is documented in the documentation. You can either use curl or postman.

**Comment by UntouchedWagons** [comment]
Well your containers are only for amd64 platform, not ARM or whatever the raspberry pi uses which is why I was trying to build the container myself.

**Comment by mlgupta** [comment]
I am looking into the option of building an image for ARM. I Will let you know how it goes.

**Comment by mlgupta** [comment]
@UntouchedWagons, set the build now using github actions. That means the support of various platforms. Builds for all the platforms are now available on the docker hub. Let me know how it goes. 

Cheers!

**Comment by UntouchedWagons** [comment]
Yup I've got Keyper running on my raspberry pi.
