### ISSUE TITLE
Cannot restart container, `can't rename 'keyper': No such file or directory`, have to remove and re-add container

### ISSUE THREAD

**Issue by UntouchedWagons** [dbsentry/keyper-docker#4]
For some particular reason I cannot restart keyper-docker, either using the docker command line or via portainer:

```
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/default.yaml
To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
/container/tools/run:295: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  env_vars = yaml.load(f)
*** Running /container/run/startup/gunicorn...
Setting UID/GID for nginx to 500/500
mv: can't rename 'keyper': No such file or directory
*** /container/run/startup/gunicorn failed with status 1
*** In SystemExit
*** In finally
*** Killing all processes...
```

The only way I can get keyper to start is by removing the container and then re-running ```docker-compose up -d```. My docker-compose.yaml file:

```version: '3.6'

services:
  keyper:
    image: dbsentry/keyper
    container_name: keyper
    restart: unless-stopped
    volumes:
      - /docker/keyper/appdata/slapd.d:/etc/openldap/slapd.d
      - /docker/keyper/appdata/ldap:/var/lib/openldap/openldap-data
      - /docker/keyper/appdata/nginx:/etc/nginx/certs
    environment:
      - HOSTNAME=keyper.untouchedwagons.site
      - NGINX_UID=500
      - NGINX_GID=500
    ports:
      - 380:80
      - 3443:443
      - 389:389
      - 636:636
```

This is running in my docker VM, not on a raspberry pi.

**Comment by mlgupta** [comment]
It is failing at ```mv keyper /var/www``` line while in ```/container/service/gunicorn/assets``` directory. 

Would you start the container without starting the services and post the content of ```/container/service/gunicorn/assets``` please.

To start a container without starting services:

```console
$ docker run -p 8080:80 -p 8443:443 -it dbsentry/keyper -s -p
```
The above should drop you in the running container's shell.

Thx

**Comment by UntouchedWagons** [comment]
```
bash-5.0# ls /container/service/gunicorn/assets
keyper  sshca
```

**Comment by mlgupta** [comment]
Would you also confirm the version of the container you are trying to restart please

**Comment by UntouchedWagons** [comment]
I don't know how to find the container version. I pulled the image about 4 hours ago so probably 0.2.1

**Comment by mlgupta** [comment]
Can you send me the exact CLI when you get this error. Let me see if I can reproduce it

**Comment by UntouchedWagons** [comment]
```
$ docker-compose up
Starting keyper ... done
Attaching to keyper
keyper    | *** CONTAINER_LOG_LEVEL = 3 (info)
keyper    | *** Set environment for startup files
keyper    | *** Environment files will be proccessed in this order :
keyper    | Caution: previously defined variables will not be overriden.
keyper    | /container/environment/default.yaml
keyper    |
keyper    | To see how this files are processed and environment variables values,
keyper    | run this container with '--loglevel debug'
keyper    | /container/tools/run:295: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
keyper    |   env_vars = yaml.load(f)
keyper    | *** Running /container/run/startup/gunicorn...
keyper    | Setting UID/GID for nginx to 500/500
keyper    | mv: can't rename 'keyper': No such file or directory
keyper    | *** /container/run/startup/gunicorn failed with status 1
keyper    |
keyper    | *** In SystemExit
keyper    | *** In finally
keyper    | *** Killing all processes...
^CGracefully stopping... (press Ctrl+C again to force)
Stopping keyper ... done
```

I'm not sure if this is what you want. The container already exists, but was stopped.

**Comment by mlgupta** [comment]
See if you are bit by this issue:

https://stackoverflow.com/questions/44461035/docker-compose-keeps-using-old-image-content

**Comment by UntouchedWagons** [comment]
Hmm I don't think so If I run ```docker image prune``` it says zero bytes reclaimed. If I delete the container, prune images and then run ```docker-compose up``` docker downloads the needed images. Then I stop the container, run ```docker-compose up``` again it fails with "Can't rename 'keyper'"

[Edit] If I run ```docker-compose up --force-recreate``` the container starts up just fine.

**Comment by mlgupta** [comment]
So, it seems that docker-compose stops the container and then tries to use the same image to restart. And, the way services works is that all the static files are stored under assets directory. During  startup these directories are moved to appropriate destination (for e.g. gunicorn/assets/keyper is moved to /var/www/keyper.

Once the directory is moved it is not available at source and hence the mv command fails on the subsequent startup. I'll have to twek the script to make it work for this condition.

**Comment by UntouchedWagons** [comment]
Would simply copying the folder work rather than moving it?

**Comment by mlgupta** [comment]
Working on it.

**Comment by mlgupta** [comment]
This has been taken care of.

**Comment by UntouchedWagons** [comment]
Nice. Thanks
